/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ckja.realworld.api;

import com.ckja.realworld.model.CreateArticleRequest;
import com.ckja.realworld.model.GenericErrorModel;
import com.ckja.realworld.model.SingleArticleResponse;
import com.ckja.realworld.model.MultipleArticlesResponse;
import org.springframework.lang.Nullable;
import com.ckja.realworld.model.UpdateArticleRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-03-01T21:06:09.127675+09:00[Asia/Tokyo]", comments = "Generator version: 7.20.0")
@Validated
@Tag(name = "Articles", description = "the Articles API")
public interface ArticlesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_CREATE_ARTICLE = "/articles";
    /**
     * POST /articles : Create an article
     * Create an article. Auth is required
     *
     * @param article Article to create (required)
     * @return Single article (status code 201)
     *         or Unauthorized (status code 401)
     *         or Conflict - resource already exists (status code 409)
     *         or Unexpected error (status code 422)
     */
    @Operation(
        operationId = "createArticle",
        summary = "Create an article",
        description = "Create an article. Auth is required",
        tags = { "Articles" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Single article", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SingleArticleResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict - resource already exists", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "422", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            })
        },
        security = {
            @SecurityRequirement(name = "Token")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ArticlesApi.PATH_CREATE_ARTICLE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<SingleArticleResponse> _createArticle(
        @Parameter(name = "article", description = "Article to create", required = true) @Valid @RequestBody CreateArticleRequest article
    ) {
        return createArticle(article);
    }

    // Override this method
    default  ResponseEntity<SingleArticleResponse> createArticle(CreateArticleRequest article) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"article\" : { \"tagList\" : [ \"tagList\", \"tagList\" ], \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"author\" : { \"image\" : \"image\", \"following\" : true, \"bio\" : \"bio\", \"username\" : \"username\" }, \"description\" : \"description\", \"title\" : \"title\", \"body\" : \"body\", \"favoritesCount\" : 0, \"slug\" : \"slug\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"favorited\" : true } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_DELETE_ARTICLE = "/articles/{slug}";
    /**
     * DELETE /articles/{slug} : Delete an article
     * Delete an article. Auth is required
     *
     * @param slug Slug of the article to delete (required)
     * @return No content (status code 204)
     *         or Unauthorized (status code 401)
     *         or Forbidden. The error key identifies the resource type (article, comment, etc.) (status code 403)
     *         or Not Found. The error key identifies the resource type (article, profile, comment, etc.) (status code 404)
     *         or Unexpected error (status code 422)
     */
    @Operation(
        operationId = "deleteArticle",
        summary = "Delete an article",
        description = "Delete an article. Auth is required",
        tags = { "Articles" },
        responses = {
            @ApiResponse(responseCode = "204", description = "No content"),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden. The error key identifies the resource type (article, comment, etc.)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found. The error key identifies the resource type (article, profile, comment, etc.)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "422", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            })
        },
        security = {
            @SecurityRequirement(name = "Token")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = ArticlesApi.PATH_DELETE_ARTICLE,
        produces = { "application/json" }
    )
    default ResponseEntity<Void> _deleteArticle(
        @NotNull @Parameter(name = "slug", description = "Slug of the article to delete", required = true, in = ParameterIn.PATH) @PathVariable("slug") String slug
    ) {
        return deleteArticle(slug);
    }

    // Override this method
    default  ResponseEntity<Void> deleteArticle(String slug) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_ARTICLE = "/articles/{slug}";
    /**
     * GET /articles/{slug} : Get an article
     * Get an article. Auth not required
     *
     * @param slug Slug of the article to get (required)
     * @return Single article (status code 200)
     *         or Not Found. The error key identifies the resource type (article, profile, comment, etc.) (status code 404)
     *         or Unexpected error (status code 422)
     */
    @Operation(
        operationId = "getArticle",
        summary = "Get an article",
        description = "Get an article. Auth not required",
        tags = { "Articles" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Single article", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SingleArticleResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found. The error key identifies the resource type (article, profile, comment, etc.)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "422", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ArticlesApi.PATH_GET_ARTICLE,
        produces = { "application/json" }
    )
    default ResponseEntity<SingleArticleResponse> _getArticle(
        @NotNull @Parameter(name = "slug", description = "Slug of the article to get", required = true, in = ParameterIn.PATH) @PathVariable("slug") String slug
    ) {
        return getArticle(slug);
    }

    // Override this method
    default  ResponseEntity<SingleArticleResponse> getArticle(String slug) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"article\" : { \"tagList\" : [ \"tagList\", \"tagList\" ], \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"author\" : { \"image\" : \"image\", \"following\" : true, \"bio\" : \"bio\", \"username\" : \"username\" }, \"description\" : \"description\", \"title\" : \"title\", \"body\" : \"body\", \"favoritesCount\" : 0, \"slug\" : \"slug\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"favorited\" : true } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_ARTICLES = "/articles";
    /**
     * GET /articles : Get recent articles globally
     * Get most recent articles globally. Use query parameters to filter results. Auth is optional
     *
     * @param tag Filter by tag (optional)
     * @param author Filter by author (username) (optional)
     * @param favorited Filter by favorites of a user (username) (optional)
     * @param offset The number of items to skip before starting to collect the result set. (optional)
     * @param limit The numbers of items to return. (optional, default to 20)
     * @return Multiple articles (status code 200)
     *         or Unauthorized (status code 401)
     *         or Unexpected error (status code 422)
     */
    @Operation(
        operationId = "getArticles",
        summary = "Get recent articles globally",
        description = "Get most recent articles globally. Use query parameters to filter results. Auth is optional",
        tags = { "Articles" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Multiple articles", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = MultipleArticlesResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "422", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ArticlesApi.PATH_GET_ARTICLES,
        produces = { "application/json" }
    )
    default ResponseEntity<MultipleArticlesResponse> _getArticles(
        @Parameter(name = "tag", description = "Filter by tag", in = ParameterIn.QUERY) @Valid @RequestParam(value = "tag", required = false) @Nullable String tag,
        @Parameter(name = "author", description = "Filter by author (username)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "author", required = false) @Nullable String author,
        @Parameter(name = "favorited", description = "Filter by favorites of a user (username)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "favorited", required = false) @Nullable String favorited,
        @Min(value = 0) @Parameter(name = "offset", description = "The number of items to skip before starting to collect the result set.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "offset", required = false) @Nullable Integer offset,
        @Min(value = 1) @Parameter(name = "limit", description = "The numbers of items to return.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false, defaultValue = "20") Integer limit
    ) {
        return getArticles(tag, author, favorited, offset, limit);
    }

    // Override this method
    default  ResponseEntity<MultipleArticlesResponse> getArticles(String tag, String author, String favorited, Integer offset, Integer limit) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"articlesCount\" : 6, \"articles\" : [ { \"tagList\" : [ \"tagList\", \"tagList\" ], \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"author\" : { \"image\" : \"image\", \"following\" : true, \"bio\" : \"bio\", \"username\" : \"username\" }, \"description\" : \"description\", \"title\" : \"title\", \"favoritesCount\" : 0, \"slug\" : \"slug\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"favorited\" : true }, { \"tagList\" : [ \"tagList\", \"tagList\" ], \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"author\" : { \"image\" : \"image\", \"following\" : true, \"bio\" : \"bio\", \"username\" : \"username\" }, \"description\" : \"description\", \"title\" : \"title\", \"favoritesCount\" : 0, \"slug\" : \"slug\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"favorited\" : true } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_ARTICLES_FEED = "/articles/feed";
    /**
     * GET /articles/feed : Get recent articles from users you follow
     * Get most recent articles from users you follow. Use query parameters to limit. Auth is required
     *
     * @param offset The number of items to skip before starting to collect the result set. (optional)
     * @param limit The numbers of items to return. (optional, default to 20)
     * @return Multiple articles (status code 200)
     *         or Unauthorized (status code 401)
     *         or Unexpected error (status code 422)
     */
    @Operation(
        operationId = "getArticlesFeed",
        summary = "Get recent articles from users you follow",
        description = "Get most recent articles from users you follow. Use query parameters to limit. Auth is required",
        tags = { "Articles" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Multiple articles", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = MultipleArticlesResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "422", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            })
        },
        security = {
            @SecurityRequirement(name = "Token")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ArticlesApi.PATH_GET_ARTICLES_FEED,
        produces = { "application/json" }
    )
    default ResponseEntity<MultipleArticlesResponse> _getArticlesFeed(
        @Min(value = 0) @Parameter(name = "offset", description = "The number of items to skip before starting to collect the result set.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "offset", required = false) @Nullable Integer offset,
        @Min(value = 1) @Parameter(name = "limit", description = "The numbers of items to return.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false, defaultValue = "20") Integer limit
    ) {
        return getArticlesFeed(offset, limit);
    }

    // Override this method
    default  ResponseEntity<MultipleArticlesResponse> getArticlesFeed(Integer offset, Integer limit) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"articlesCount\" : 6, \"articles\" : [ { \"tagList\" : [ \"tagList\", \"tagList\" ], \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"author\" : { \"image\" : \"image\", \"following\" : true, \"bio\" : \"bio\", \"username\" : \"username\" }, \"description\" : \"description\", \"title\" : \"title\", \"favoritesCount\" : 0, \"slug\" : \"slug\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"favorited\" : true }, { \"tagList\" : [ \"tagList\", \"tagList\" ], \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"author\" : { \"image\" : \"image\", \"following\" : true, \"bio\" : \"bio\", \"username\" : \"username\" }, \"description\" : \"description\", \"title\" : \"title\", \"favoritesCount\" : 0, \"slug\" : \"slug\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"favorited\" : true } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_UPDATE_ARTICLE = "/articles/{slug}";
    /**
     * PUT /articles/{slug} : Update an article
     * Update an article. Auth is required
     *
     * @param slug Slug of the article to update (required)
     * @param article Article to update (required)
     * @return Single article (status code 200)
     *         or Unauthorized (status code 401)
     *         or Forbidden. The error key identifies the resource type (article, comment, etc.) (status code 403)
     *         or Not Found. The error key identifies the resource type (article, profile, comment, etc.) (status code 404)
     *         or Unexpected error (status code 422)
     */
    @Operation(
        operationId = "updateArticle",
        summary = "Update an article",
        description = "Update an article. Auth is required",
        tags = { "Articles" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Single article", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SingleArticleResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden. The error key identifies the resource type (article, comment, etc.)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found. The error key identifies the resource type (article, profile, comment, etc.)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "422", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            })
        },
        security = {
            @SecurityRequirement(name = "Token")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = ArticlesApi.PATH_UPDATE_ARTICLE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<SingleArticleResponse> _updateArticle(
        @NotNull @Parameter(name = "slug", description = "Slug of the article to update", required = true, in = ParameterIn.PATH) @PathVariable("slug") String slug,
        @Parameter(name = "article", description = "Article to update", required = true) @Valid @RequestBody UpdateArticleRequest article
    ) {
        return updateArticle(slug, article);
    }

    // Override this method
    default  ResponseEntity<SingleArticleResponse> updateArticle(String slug, UpdateArticleRequest article) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"article\" : { \"tagList\" : [ \"tagList\", \"tagList\" ], \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"author\" : { \"image\" : \"image\", \"following\" : true, \"bio\" : \"bio\", \"username\" : \"username\" }, \"description\" : \"description\", \"title\" : \"title\", \"body\" : \"body\", \"favoritesCount\" : 0, \"slug\" : \"slug\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"favorited\" : true } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
