/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ckja.realworld.api;

import com.ckja.realworld.model.CreateArticleCommentRequest;
import com.ckja.realworld.model.GenericErrorModel;
import com.ckja.realworld.model.SingleCommentResponse;
import com.ckja.realworld.model.MultipleCommentsResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-03-01T21:06:09.127675+09:00[Asia/Tokyo]", comments = "Generator version: 7.20.0")
@Validated
@Tag(name = "Comments", description = "the Comments API")
public interface CommentsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_CREATE_ARTICLE_COMMENT = "/articles/{slug}/comments";
    /**
     * POST /articles/{slug}/comments : Create a comment for an article
     * Create a comment for an article. Auth is required
     *
     * @param slug Slug of the article that you want to create a comment for (required)
     * @param comment Comment you want to create (required)
     * @return Single comment (status code 201)
     *         or Unauthorized (status code 401)
     *         or Not Found. The error key identifies the resource type (article, profile, comment, etc.) (status code 404)
     *         or Unexpected error (status code 422)
     */
    @Operation(
        operationId = "createArticleComment",
        summary = "Create a comment for an article",
        description = "Create a comment for an article. Auth is required",
        tags = { "Comments" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Single comment", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SingleCommentResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found. The error key identifies the resource type (article, profile, comment, etc.)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "422", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            })
        },
        security = {
            @SecurityRequirement(name = "Token")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = CommentsApi.PATH_CREATE_ARTICLE_COMMENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<SingleCommentResponse> _createArticleComment(
        @NotNull @Parameter(name = "slug", description = "Slug of the article that you want to create a comment for", required = true, in = ParameterIn.PATH) @PathVariable("slug") String slug,
        @Parameter(name = "comment", description = "Comment you want to create", required = true) @Valid @RequestBody CreateArticleCommentRequest comment
    ) {
        return createArticleComment(slug, comment);
    }

    // Override this method
    default  ResponseEntity<SingleCommentResponse> createArticleComment(String slug, CreateArticleCommentRequest comment) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"comment\" : { \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"author\" : { \"image\" : \"image\", \"following\" : true, \"bio\" : \"bio\", \"username\" : \"username\" }, \"id\" : 0, \"body\" : \"body\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_DELETE_ARTICLE_COMMENT = "/articles/{slug}/comments/{id}";
    /**
     * DELETE /articles/{slug}/comments/{id} : Delete a comment for an article
     * Delete a comment for an article. Auth is required
     *
     * @param slug Slug of the article that you want to delete a comment for (required)
     * @param id ID of the comment you want to delete (required)
     * @return No content (status code 204)
     *         or Unauthorized (status code 401)
     *         or Forbidden. The error key identifies the resource type (article, comment, etc.) (status code 403)
     *         or Not Found. The error key identifies the resource type (article, profile, comment, etc.) (status code 404)
     *         or Unexpected error (status code 422)
     */
    @Operation(
        operationId = "deleteArticleComment",
        summary = "Delete a comment for an article",
        description = "Delete a comment for an article. Auth is required",
        tags = { "Comments" },
        responses = {
            @ApiResponse(responseCode = "204", description = "No content"),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden. The error key identifies the resource type (article, comment, etc.)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found. The error key identifies the resource type (article, profile, comment, etc.)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "422", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            })
        },
        security = {
            @SecurityRequirement(name = "Token")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = CommentsApi.PATH_DELETE_ARTICLE_COMMENT,
        produces = { "application/json" }
    )
    default ResponseEntity<Void> _deleteArticleComment(
        @NotNull @Parameter(name = "slug", description = "Slug of the article that you want to delete a comment for", required = true, in = ParameterIn.PATH) @PathVariable("slug") String slug,
        @NotNull @Parameter(name = "id", description = "ID of the comment you want to delete", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    ) {
        return deleteArticleComment(slug, id);
    }

    // Override this method
    default  ResponseEntity<Void> deleteArticleComment(String slug, Integer id) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_ARTICLE_COMMENTS = "/articles/{slug}/comments";
    /**
     * GET /articles/{slug}/comments : Get comments for an article
     * Get the comments for an article. Auth is optional
     *
     * @param slug Slug of the article that you want to get comments for (required)
     * @return Multiple comments (status code 200)
     *         or Unauthorized (status code 401)
     *         or Not Found. The error key identifies the resource type (article, profile, comment, etc.) (status code 404)
     *         or Unexpected error (status code 422)
     */
    @Operation(
        operationId = "getArticleComments",
        summary = "Get comments for an article",
        description = "Get the comments for an article. Auth is optional",
        tags = { "Comments" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Multiple comments", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = MultipleCommentsResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found. The error key identifies the resource type (article, profile, comment, etc.)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "422", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = CommentsApi.PATH_GET_ARTICLE_COMMENTS,
        produces = { "application/json" }
    )
    default ResponseEntity<MultipleCommentsResponse> _getArticleComments(
        @NotNull @Parameter(name = "slug", description = "Slug of the article that you want to get comments for", required = true, in = ParameterIn.PATH) @PathVariable("slug") String slug
    ) {
        return getArticleComments(slug);
    }

    // Override this method
    default  ResponseEntity<MultipleCommentsResponse> getArticleComments(String slug) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"comments\" : [ { \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"author\" : { \"image\" : \"image\", \"following\" : true, \"bio\" : \"bio\", \"username\" : \"username\" }, \"id\" : 0, \"body\" : \"body\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }, { \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"author\" : { \"image\" : \"image\", \"following\" : true, \"bio\" : \"bio\", \"username\" : \"username\" }, \"id\" : 0, \"body\" : \"body\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
