/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ckja.realworld.api;

import com.ckja.realworld.model.GenericErrorModel;
import com.ckja.realworld.model.SingleArticleResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-03-01T21:06:09.127675+09:00[Asia/Tokyo]", comments = "Generator version: 7.20.0")
@Validated
@Tag(name = "Favorites", description = "the Favorites API")
public interface FavoritesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_CREATE_ARTICLE_FAVORITE = "/articles/{slug}/favorite";
    /**
     * POST /articles/{slug}/favorite : Favorite an article
     * Favorite an article. Auth is required
     *
     * @param slug Slug of the article that you want to favorite (required)
     * @return Single article (status code 200)
     *         or Unauthorized (status code 401)
     *         or Not Found. The error key identifies the resource type (article, profile, comment, etc.) (status code 404)
     *         or Unexpected error (status code 422)
     */
    @Operation(
        operationId = "createArticleFavorite",
        summary = "Favorite an article",
        description = "Favorite an article. Auth is required",
        tags = { "Favorites" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Single article", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SingleArticleResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found. The error key identifies the resource type (article, profile, comment, etc.)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "422", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            })
        },
        security = {
            @SecurityRequirement(name = "Token")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = FavoritesApi.PATH_CREATE_ARTICLE_FAVORITE,
        produces = { "application/json" }
    )
    default ResponseEntity<SingleArticleResponse> _createArticleFavorite(
        @NotNull @Parameter(name = "slug", description = "Slug of the article that you want to favorite", required = true, in = ParameterIn.PATH) @PathVariable("slug") String slug
    ) {
        return createArticleFavorite(slug);
    }

    // Override this method
    default  ResponseEntity<SingleArticleResponse> createArticleFavorite(String slug) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"article\" : { \"tagList\" : [ \"tagList\", \"tagList\" ], \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"author\" : { \"image\" : \"image\", \"following\" : true, \"bio\" : \"bio\", \"username\" : \"username\" }, \"description\" : \"description\", \"title\" : \"title\", \"body\" : \"body\", \"favoritesCount\" : 0, \"slug\" : \"slug\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"favorited\" : true } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_DELETE_ARTICLE_FAVORITE = "/articles/{slug}/favorite";
    /**
     * DELETE /articles/{slug}/favorite : Unfavorite an article
     * Unfavorite an article. Auth is required
     *
     * @param slug Slug of the article that you want to unfavorite (required)
     * @return Single article (status code 200)
     *         or Unauthorized (status code 401)
     *         or Not Found. The error key identifies the resource type (article, profile, comment, etc.) (status code 404)
     *         or Unexpected error (status code 422)
     */
    @Operation(
        operationId = "deleteArticleFavorite",
        summary = "Unfavorite an article",
        description = "Unfavorite an article. Auth is required",
        tags = { "Favorites" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Single article", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SingleArticleResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found. The error key identifies the resource type (article, profile, comment, etc.)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "422", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            })
        },
        security = {
            @SecurityRequirement(name = "Token")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = FavoritesApi.PATH_DELETE_ARTICLE_FAVORITE,
        produces = { "application/json" }
    )
    default ResponseEntity<SingleArticleResponse> _deleteArticleFavorite(
        @NotNull @Parameter(name = "slug", description = "Slug of the article that you want to unfavorite", required = true, in = ParameterIn.PATH) @PathVariable("slug") String slug
    ) {
        return deleteArticleFavorite(slug);
    }

    // Override this method
    default  ResponseEntity<SingleArticleResponse> deleteArticleFavorite(String slug) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"article\" : { \"tagList\" : [ \"tagList\", \"tagList\" ], \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"author\" : { \"image\" : \"image\", \"following\" : true, \"bio\" : \"bio\", \"username\" : \"username\" }, \"description\" : \"description\", \"title\" : \"title\", \"body\" : \"body\", \"favoritesCount\" : 0, \"slug\" : \"slug\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"favorited\" : true } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
