/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ckja.realworld.api;

import com.ckja.realworld.model.GenericErrorModel;
import com.ckja.realworld.model.InlineObject5;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-03-01T21:06:09.127675+09:00[Asia/Tokyo]", comments = "Generator version: 7.20.0")
@Validated
@Tag(name = "Profile", description = "the Profile API")
public interface ProfileApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_FOLLOW_USER_BY_USERNAME = "/profiles/{username}/follow";
    /**
     * POST /profiles/{username}/follow : Follow a user
     * Follow a user by username
     *
     * @param username Username of the profile you want to follow (required)
     * @return Profile (status code 200)
     *         or Unauthorized (status code 401)
     *         or Not Found. The error key identifies the resource type (article, profile, comment, etc.) (status code 404)
     *         or Unexpected error (status code 422)
     */
    @Operation(
        operationId = "followUserByUsername",
        summary = "Follow a user",
        description = "Follow a user by username",
        tags = { "Profile" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Profile", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InlineObject5.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found. The error key identifies the resource type (article, profile, comment, etc.)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "422", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            })
        },
        security = {
            @SecurityRequirement(name = "Token")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ProfileApi.PATH_FOLLOW_USER_BY_USERNAME,
        produces = { "application/json" }
    )
    default ResponseEntity<InlineObject5> _followUserByUsername(
        @NotNull @Parameter(name = "username", description = "Username of the profile you want to follow", required = true, in = ParameterIn.PATH) @PathVariable("username") String username
    ) {
        return followUserByUsername(username);
    }

    // Override this method
    default  ResponseEntity<InlineObject5> followUserByUsername(String username) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"profile\" : { \"image\" : \"image\", \"following\" : true, \"bio\" : \"bio\", \"username\" : \"username\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_PROFILE_BY_USERNAME = "/profiles/{username}";
    /**
     * GET /profiles/{username} : Get a profile
     * Get a profile of a user of the system. Auth is optional
     *
     * @param username Username of the profile to get (required)
     * @return Profile (status code 200)
     *         or Unauthorized (status code 401)
     *         or Not Found. The error key identifies the resource type (article, profile, comment, etc.) (status code 404)
     *         or Unexpected error (status code 422)
     */
    @Operation(
        operationId = "getProfileByUsername",
        summary = "Get a profile",
        description = "Get a profile of a user of the system. Auth is optional",
        tags = { "Profile" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Profile", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InlineObject5.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found. The error key identifies the resource type (article, profile, comment, etc.)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "422", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ProfileApi.PATH_GET_PROFILE_BY_USERNAME,
        produces = { "application/json" }
    )
    default ResponseEntity<InlineObject5> _getProfileByUsername(
        @NotNull @Parameter(name = "username", description = "Username of the profile to get", required = true, in = ParameterIn.PATH) @PathVariable("username") String username
    ) {
        return getProfileByUsername(username);
    }

    // Override this method
    default  ResponseEntity<InlineObject5> getProfileByUsername(String username) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"profile\" : { \"image\" : \"image\", \"following\" : true, \"bio\" : \"bio\", \"username\" : \"username\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_UNFOLLOW_USER_BY_USERNAME = "/profiles/{username}/follow";
    /**
     * DELETE /profiles/{username}/follow : Unfollow a user
     * Unfollow a user by username
     *
     * @param username Username of the profile you want to unfollow (required)
     * @return Profile (status code 200)
     *         or Unauthorized (status code 401)
     *         or Not Found. The error key identifies the resource type (article, profile, comment, etc.) (status code 404)
     *         or Unexpected error (status code 422)
     */
    @Operation(
        operationId = "unfollowUserByUsername",
        summary = "Unfollow a user",
        description = "Unfollow a user by username",
        tags = { "Profile" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Profile", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InlineObject5.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found. The error key identifies the resource type (article, profile, comment, etc.)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "422", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            })
        },
        security = {
            @SecurityRequirement(name = "Token")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = ProfileApi.PATH_UNFOLLOW_USER_BY_USERNAME,
        produces = { "application/json" }
    )
    default ResponseEntity<InlineObject5> _unfollowUserByUsername(
        @NotNull @Parameter(name = "username", description = "Username of the profile you want to unfollow", required = true, in = ParameterIn.PATH) @PathVariable("username") String username
    ) {
        return unfollowUserByUsername(username);
    }

    // Override this method
    default  ResponseEntity<InlineObject5> unfollowUserByUsername(String username) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"profile\" : { \"image\" : \"image\", \"following\" : true, \"bio\" : \"bio\", \"username\" : \"username\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
