/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ckja.realworld.api;

import com.ckja.realworld.model.CreateUserRequest;
import com.ckja.realworld.model.GenericErrorModel;
import com.ckja.realworld.model.InlineObject6;
import com.ckja.realworld.model.LoginRequest;
import com.ckja.realworld.model.UpdateCurrentUserRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-03-01T21:06:09.127675+09:00[Asia/Tokyo]", comments = "Generator version: 7.20.0")
@Validated
@Tag(name = "User and Authentication", description = "the User and Authentication API")
public interface UserAndAuthenticationApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_CREATE_USER = "/users";
    /**
     * POST /users
     * Register a new user
     *
     * @param body Details of the new user to register (required)
     * @return User (status code 201)
     *         or Conflict - resource already exists (status code 409)
     *         or Unexpected error (status code 422)
     */
    @Operation(
        operationId = "createUser",
        description = "Register a new user",
        tags = { "User and Authentication" },
        responses = {
            @ApiResponse(responseCode = "201", description = "User", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InlineObject6.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict - resource already exists", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "422", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = UserAndAuthenticationApi.PATH_CREATE_USER,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<InlineObject6> _createUser(
        @Parameter(name = "body", description = "Details of the new user to register", required = true) @Valid @RequestBody CreateUserRequest body
    ) {
        return createUser(body);
    }

    // Override this method
    default  ResponseEntity<InlineObject6> createUser(CreateUserRequest body) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"user\" : { \"image\" : \"image\", \"bio\" : \"bio\", \"email\" : \"email\", \"token\" : \"token\", \"username\" : \"username\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_CURRENT_USER = "/user";
    /**
     * GET /user : Get current user
     * Gets the currently logged-in user
     *
     * @return User (status code 200)
     *         or Unauthorized (status code 401)
     *         or Unexpected error (status code 422)
     */
    @Operation(
        operationId = "getCurrentUser",
        summary = "Get current user",
        description = "Gets the currently logged-in user",
        tags = { "User and Authentication" },
        responses = {
            @ApiResponse(responseCode = "200", description = "User", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InlineObject6.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "422", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            })
        },
        security = {
            @SecurityRequirement(name = "Token")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = UserAndAuthenticationApi.PATH_GET_CURRENT_USER,
        produces = { "application/json" }
    )
    default ResponseEntity<InlineObject6> _getCurrentUser(
        
    ) {
        return getCurrentUser();
    }

    // Override this method
    default  ResponseEntity<InlineObject6> getCurrentUser() {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"user\" : { \"image\" : \"image\", \"bio\" : \"bio\", \"email\" : \"email\", \"token\" : \"token\", \"username\" : \"username\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_LOGIN = "/users/login";
    /**
     * POST /users/login : Existing user login
     * Login for existing user
     *
     * @param body Credentials to use (required)
     * @return User (status code 200)
     *         or Unauthorized (status code 401)
     *         or Unexpected error (status code 422)
     */
    @Operation(
        operationId = "login",
        summary = "Existing user login",
        description = "Login for existing user",
        tags = { "User and Authentication" },
        responses = {
            @ApiResponse(responseCode = "200", description = "User", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InlineObject6.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "422", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = UserAndAuthenticationApi.PATH_LOGIN,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<InlineObject6> _login(
        @Parameter(name = "body", description = "Credentials to use", required = true) @Valid @RequestBody LoginRequest body
    ) {
        return login(body);
    }

    // Override this method
    default  ResponseEntity<InlineObject6> login(LoginRequest body) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"user\" : { \"image\" : \"image\", \"bio\" : \"bio\", \"email\" : \"email\", \"token\" : \"token\", \"username\" : \"username\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_UPDATE_CURRENT_USER = "/user";
    /**
     * PUT /user : Update current user
     * Updated user information for current user
     *
     * @param body User details to update. At least **one** field is required. (required)
     * @return User (status code 200)
     *         or Unauthorized (status code 401)
     *         or Unexpected error (status code 422)
     */
    @Operation(
        operationId = "updateCurrentUser",
        summary = "Update current user",
        description = "Updated user information for current user",
        tags = { "User and Authentication" },
        responses = {
            @ApiResponse(responseCode = "200", description = "User", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InlineObject6.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            }),
            @ApiResponse(responseCode = "422", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenericErrorModel.class))
            })
        },
        security = {
            @SecurityRequirement(name = "Token")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = UserAndAuthenticationApi.PATH_UPDATE_CURRENT_USER,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<InlineObject6> _updateCurrentUser(
        @Parameter(name = "body", description = "User details to update. At least **one** field is required.", required = true) @Valid @RequestBody UpdateCurrentUserRequest body
    ) {
        return updateCurrentUser(body);
    }

    // Override this method
    default  ResponseEntity<InlineObject6> updateCurrentUser(UpdateCurrentUserRequest body) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"user\" : { \"image\" : \"image\", \"bio\" : \"bio\", \"email\" : \"email\", \"token\" : \"token\", \"username\" : \"username\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"errors\" : { \"key\" : [ \"errors\", \"errors\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
